# my_example_test

name: My Example Test One

# start docker file ubuntu latest

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

      
jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Test Message
      run : echo "Test Message from job my_example_test.yaml"
  
  my_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Test Message
      run : echo "Prod Message from job my_example_test.yaml"
