
# my_example_test

name: My Example Test

# start docker file ubuntu latest
on:
  push:
    branches:
      - master
      
jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Test Message
      run : echo "Test Message from job my_example_test.yaml"
  
  my_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Test Message
      run : echo "Prod Message from job my_example_test.yaml"
      
  
